### ISSUE TITLE
EFL not building

### ISSUE THREAD

**Issue by G-Guillard** [Ponce/slackbuilds#108]
Hi,

Did anyone manage to build EFL ?  I can't manage to build it on a fresh Slackware current install :

```
[3321/3705] /usr/bin/env EFL_RUN_IN_TREE=1 /distrobis/tmp/SBo/efl-1.25/build/src/bin/edje/edje_cc -beta -fastcomp -id /distrobis/tmp/SBo/efl-1.25/src/examples/edje -fd /distrobis/tmp/SBo/efl-1.25/src/examples/edje -sd /distrobis/tmp/SBo/efl-1.25/src/examples/edje -vd /distrobis/tmp/SBo/efl-1.25/src/examples/edje -dd /distrobis/tmp/SBo/efl-1.25/src/examples/edje -md /distrobis/tmp/SBo/efl-1.25/src/examples/edje -td /distrobis/tmp/SBo/efl-1.25/src/examples/edje ../src/examples/edje/text.edc src/examples/edje/text.edj
FAILED: src/examples/edje/text.edj 
/usr/bin/env EFL_RUN_IN_TREE=1 /distrobis/tmp/SBo/efl-1.25/build/src/bin/edje/edje_cc -beta -fastcomp -id /distrobis/tmp/SBo/efl-1.25/src/examples/edje -fd /distrobis/tmp/SBo/efl-1.25/src/examples/edje -sd /distrobis/tmp/SBo/efl-1.25/src/examples/edje -vd /distrobis/tmp/SBo/efl-1.25/src/examples/edje -dd /distrobis/tmp/SBo/efl-1.25/src/examples/edje -md /distrobis/tmp/SBo/efl-1.25/src/examples/edje -td /distrobis/tmp/SBo/efl-1.25/src/examples/edje ../src/examples/edje/text.edc src/examples/edje/text.edj
edje_cc: Critical. Creation of .mo from .po failed.
```

I tried with the 1.24.4 version (as in the Slackbuild), with the 1.25.1 (latest found on https://download.enlightenment.org/rel/libs/efl/), and finally with the freshest git version (wich I labelled 1.25 here for convenience) but they all failed on the same error, which is not quite verbose on what the issue might be.

FWIW, I also [reported this issue upstream](https://phab.enlightenment.org/T8925).

**Comment by Ponce** [comment]
I'm sorry but I'm not able to reproduce this: here efl builds fine on slackware-current 32 and 64bit.
the only thing that I can think about is that you missed reading the instructions in the efl README file
```
This package supersedes the following obsolete packages:
	e_dbus ecore edje eet efreet eina eio elementary embryo emotion ethumb evas

Please remove the above packages before installing this one.

NOTE:  You must remove any previous installation of efl before running this
script, otherwise the build will fail.
```

**Comment by G-Guillard** [comment]
Ok, thanks.  I followed the README instructions, AFAICS none of these packages is installed.  I believe I'm missing some package but the error message is not very helpful to identify which one.  Hopefully they will have an idea upstream, I will report it back here.
