### ISSUE TITLE
kernel 5.12.9

### ISSUE THREAD

**Issue by aianson** [Ponce/slackbuilds#123]
Since the release of the 5.12.9 kernel this module is not working for me. I see a patch for the 5.12 kernel being used for the arch linux AUR build. We may need to use it, or something like it as well.

My issue is in regards to nvidia-legacy390-kernel.

**Comment by Ponce** [comment]
fixes are pushed in my git branch on SBo, thanks for the report!

https://git.slackbuilds.org/slackbuilds/log/?h=ponce
