### ISSUE TITLE
BeautifulSoup4 fails to build

### ISSUE THREAD

**Issue by ozanbaba** [Ponce/slackbuilds#135]
BeautifulSoup4 fails to build with below error:
`error in beautifulsoup4 setup command: use_2to3 is invalid.`

**Comment by RSKYS** [comment]
This problem is fixed

**Comment by RSKYS** [comment]
This issue has been resolved.

**Comment by Ponce** [comment]
yes, it's solved by the revert to python-3.9 in current.
