### ISSUE TITLE
seafile does not build

### ISSUE THREAD

**Issue by stroudmw** [Ponce/slackbuilds#137]
I am trying to install the seafile client. I start with seafile. This happens:

`make[2]: Entering directory '/tmp/SBo/seafile-6.2.5/daemon'
gcc -DHAVE_CONFIG_H -I. -I..    -DPKGDATADIR=\"/usr/share/seafile\" -DPACKAGE_DATA_DIR=\""/usr/share/seafile"\" -DSEAFILE_CLIENT -I../include -I../lib -I../lib -I../common -pthread -I/tmp/SBo/package-libsearpc/usr/include -I/tmp/SBo/package-libsearpc/usr/include/searpc -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -Wall -O2 -fPIC -MT seaf-daemon.o -MD -MP -MF .deps/seaf-daemon.Tpo -c -o seaf-daemon.o seaf-daemon.c
mv -f .deps/seaf-daemon.Tpo .deps/seaf-daemon.Po
gcc -DHAVE_CONFIG_H -I. -I..    -DPKGDATADIR=\"/usr/share/seafile\" -DPACKAGE_DATA_DIR=\""/usr/share/seafile"\" -DSEAFILE_CLIENT -I../include -I../lib -I../lib -I../common -pthread -I/tmp/SBo/package-libsearpc/usr/include -I/tmp/SBo/package-libsearpc/usr/include/searpc -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -Wall -O2 -fPIC -MT job-mgr.o -MD -MP -MF .deps/job-mgr.Tpo -c -o job-mgr.o job-mgr.c
mv -f .deps/job-mgr.Tpo .deps/job-mgr.Po
gcc -DHAVE_CONFIG_H -I. -I..    -DPKGDATADIR=\"/usr/share/seafile\" -DPACKAGE_DATA_DIR=\""/usr/share/seafile"\" -DSEAFILE_CLIENT -I../include -I../lib -I../lib -I../common -pthread -I/tmp/SBo/package-libsearpc/usr/include -I/tmp/SBo/package-libsearpc/usr/include/searpc -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -Wall -O2 -fPIC -MT timer.o -MD -MP -MF .deps/timer.Tpo -c -o timer.o timer.c
mv -f .deps/timer.Tpo .deps/timer.Po
gcc -DHAVE_CONFIG_H -I. -I..    -DPKGDATADIR=\"/usr/share/seafile\" -DPACKAGE_DATA_DIR=\""/usr/share/seafile"\" -DSEAFILE_CLIENT -I../include -I../lib -I../lib -I../common -pthread -I/tmp/SBo/package-libsearpc/usr/include -I/tmp/SBo/package-libsearpc/usr/include/searpc -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -Wall -O2 -fPIC -MT cevent.o -MD -MP -MF .deps/cevent.Tpo -c -o cevent.o cevent.c
mv -f .deps/cevent.Tpo .deps/cevent.Po
gcc -DHAVE_CONFIG_H -I. -I..    -DPKGDATADIR=\"/usr/share/seafile\" -DPACKAGE_DATA_DIR=\""/usr/share/seafile"\" -DSEAFILE_CLIENT -I../include -I../lib -I../lib -I../common -pthread -I/tmp/SBo/package-libsearpc/usr/include -I/tmp/SBo/package-libsearpc/usr/include/searpc -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -Wall -O2 -fPIC -MT http-tx-mgr.o -MD -MP -MF .deps/http-tx-mgr.Tpo -c -o http-tx-mgr.o http-tx-mgr.c
http-tx-mgr.c: In function ‘curl_error_to_http_task_error’:
http-tx-mgr.c:1139:5: error: duplicate case value
 1139 |     case CURLE_SSL_CACERT:
      |     ^~~~
http-tx-mgr.c:1137:5: note: previously used here
 1137 |     case CURLE_PEER_FAILED_VERIFICATION:
      |     ^~~~
make[2]: *** [Makefile:606: http-tx-mgr.o] Error 1
make[2]: Leaving directory '/tmp/SBo/seafile-6.2.5/daemon'
make[1]: *** [Makefile:443: all-recursive] Error 1
make[1]: Leaving directory '/tmp/SBo/seafile-6.2.5'
make: *** [Makefile:375: all] Error 2

seafile:
Would you like to continue processing the rest of the
queue or would you like to abort?  If this failed
package is a dependency of another package in the queue
then it may not make sense to continue.

(Y)es to continue, (N)o to abort, (R)etry the build?: 
`

**Comment by stroudmw** [comment]
slackware-current. Fully upgraded this morning.

**Comment by Ponce** [comment]
pushed updates for this in my branch on SBo

https://git.slackbuilds.org/slackbuilds/commit/?id=5cef5c6
https://git.slackbuilds.org/slackbuilds/commit/?id=bbfd836
https://git.slackbuilds.org/slackbuilds/commit/?id=b49ab6a

thanks for the report!

**Comment by stroudmw** [comment]
I've just tried it again and get the same error. I ran` sbopkg -r` thinking that would give me the latest updates. But clearly I'm doing something very wrong!

**Comment by Ponce** [comment]
I suggest you carefully read the instructions on how to use this repository with sbopkg, the last bit in particular

https://github.com/Ponce/slackbuilds/wiki/configuring-the-current-repository-with-sbopkg
