### ISSUE TITLE
Virtualbox: Rejecting GCC 5

### ISSUE THREAD

**Issue by Xylemon** [Ponce/slackbuilds#15]
Virtualbox rejects GCC 5 and could have other problems with compiling. I found this "partial patch" here: https://www.virtualbox.org/pipermail/vbox-dev/2015-February/012862.html

Hoping it's useful to getting virtualbox compiling on Slackware Current.

**Comment by yars068** [comment]
Now, [latest virtualbox](http://download.virtualbox.org/virtualbox/5.0.14/VirtualBox-5.0.14.tar.bz2) can be built using gcc-5.3.

**Comment by Xylemon** [comment]
@yars068 yeah saw this recently but just got around to it. As a result this no longer needs to be open.
