### ISSUE TITLE
hugin build fails

### ISSUE THREAD

**Issue by fal7i** [Ponce/slackbuilds#152]
due to the lack of sys/sysctl.h since glibc 2.32 
hugin-2018.0.0 fails :
/tmp/SBo/hugin-2018.0.0/src/hugin_base/hugin_utils/platform.cpp:34:10: fatal error: sys/sysctl.h: No such file or directory
   34 | #include <sys/sysctl.h>

Fortunately hugin-2020.0.0 works fine

thanks for yours SlackBuilds

**Comment by Ponce** [comment]
I just pushed the update, thanks!
