### ISSUE TITLE
gimp feca_hdr.py issue

### ISSUE THREAD

**Issue by fal7i** [Ponce/slackbuilds#153]
Hi,
python_fu_feca_hdr plugin fails with :
TypeError: 'NoneType' object has no attribute '__getitem__'  
we can find the fix at : https://gist.github.com/rlee287/52034fd80e4e0f07fd570f2315341bd4

diff : 
52,54c52
<                         self.tile = self.drawable.get_tile2(FALSE, row, col)
<                         if self.tile is None:
<                             print("Tile is none at "+str(row)+","+str(col))
---
>                         self.tile = self.drawable.get_tile(FALSE, row, col)
68,70c66
<                         self.tile = self.drawable.get_tile2(FALSE, row, col)
<                         if self.tile is None:
<                             print("Tile is none at "+str(row)+","+str(col))
---
>                         self.tile = self.drawable.get_tile(FALSE, row, col)

tested, it works fine !

regards,
ff

**Comment by Ponce** [comment]
thanks: I had to work on it a little but I pushed the changes in my SBo branch.
