### ISSUE TITLE
OBS Studio SlackBuild is very out of date

### ISSUE THREAD

**Issue by daemonspudguy** [Ponce/slackbuilds#184]
The latest version of OBS Studio is 27.2.3

**Comment by daemonspudguy** [comment]
I made a prototype slackbuild, but I need to upload the file.

**Comment by Ponce** [comment]
hi @daemonspudguy 

obs-studio has already been updated by its maintainer to version 27.2.3 in the official SBo repository.
next time please refer directly to the respective script maintainers for updates: they decide which version is best and there might be specific reasons why a script is kept to a specific version.
