### ISSUE TITLE
gcc-12 patch for owncloud-client no longer required.

### ISSUE THREAD

**Issue by ArTourter** [Ponce/slackbuilds#188]
Hi Mateo,

the patch add to the owncloud-client slackbuild is no longer required and the script now fails in sbopkg as the change have basically already been applied in the newer version:

```
patching file src/common/asserts.h
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file src/common/asserts.h.rej
patching file src/common/vfs.h
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
6 out of 6 hunks ignored -- saving rejects to file src/common/vfs.h.rej
Cleaning up...
```
The slackbuild run and compiles just fine now from the original slackbuild script on -current.

**Comment by Ponce** [comment]
hi Greg, sorry I just spotted this: I'll remove the patch, it will go in the next global update.
thanks for the heads-up!
