### ISSUE TITLE
are fcitx5* files needed in current slackbuild repo?

### ISSUE THREAD

**Issue by rizitis** [Ponce/slackbuilds#195]
The list below shows all packages with name matching "fcitx5", which are included in Slackware current installation but also 
included in ponce current slackbuild repo.

[ installed ] - fcitx5-5.0.21-x86_64-1
[ installed ] - fcitx5-anthy-5.0.13-x86_64-1
[ installed ] - fcitx5-chinese-addons-5.0.16-x86_64-2
[ installed ] - fcitx5-configtool-5.0.16-x86_64-1
[ installed ] - fcitx5-gtk-5.0.21-x86_64-1
[ installed ] - fcitx5-hangul-5.0.10-x86_64-1
[ installed ] - fcitx5-kkc-5.0.11-x86_64-1
[ installed ] - fcitx5-m17n-5.0.11-x86_64-1
[ installed ] - fcitx5-qt-5.0.16-x86_64-1
[ installed ] - fcitx5-sayura-5.0.8-x86_64-1
[ installed ] - fcitx5-table-extra-5.0.12-x86_64-1
[ installed ] - fcitx5-table-other-5.0.10-x86_64-1
[ installed ] - fcitx5-theme-breeze-2.0.0-noarch-1
[ installed ] - fcitx5-unikey-5.0.12-x86_64-1

If Think can be removed to avoid conflicts , except if I missing something...
thank you.

**Comment by Ponce** [comment]
hi @rizitis ,

not all the packages you cite are on SBo: I checked and only the following ones need to be removed
```
  fcitx5
  fcitx5-chinese-addons
  fcitx5-configtool
  fcitx5-gtk
  fcitx5-qt
  fcitx5-table-extra
  fcitx5-table-other
```
thanks for the report!
