### ISSUE TITLE
firewalld - sbopkg - build Can't find the correct name

### ISSUE THREAD

**Issue by lpgpa** [Ponce/slackbuilds#203]
Hi, when i use 

slackpkg -i firewalld # i use Ponce Repo -

The package to download change the name, then is not possible to complete the installation.

In ./network/firewalld/firewalld.info.build

DOWNLOAD="https://github.com/firewalld/firewalld/archive/refs/tags/v1.3.0.tar.gz#/firewalld-1.3.0.tar.gz"

 The log return to check 

firewalld not found in /var/cache/sbopkg.

There the package is /var/cache/sbopkg/v1.3.0.tar.gz

Please, if this channel is not to fix it, if you can inform where to do it!

Tks

**Comment by Ponce** [comment]
hi @lpgpa ,

this is not the proper place to discuss the matter: please report the thing to the firewalld maintainer (it's listed in the firewalld.info file).
