### ISSUE TITLE
gdal patches no longer needed

### ISSUE THREAD

**Issue by ArTourter** [Ponce/slackbuilds#214]
Hi Mateo,

The libxml patches for gdal are no longer needed since I updated the slackbuild to 3.8.x.

you now get the following error when attempting to apply the patches:
```patching file port/cpl_xml_validate.cpp
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file port/cpl_xml_validate.cpp.rej
Cleaning up...
```
The package build without issues on current without any modifications to the original slackbuild script.

**Comment by Ponce** [comment]
thanks for the heads-up Greg, I'll remove them!
