### ISSUE TITLE
migrate to tenv

### ISSUE THREAD

**Issue by kvendingoldo** [Ponce/slackbuilds#220]
Hi! I found that you're using tofuenv; I'm one of the authors of this tools and we developed the better tool tenv than can manage terraform/tofu/terragrunt together. https://github.com/tofuutils/tenv
JFI

**Comment by Ponce** [comment]
hi @kvendingoldo ,

this is a fork of a public repository of third-party script for the Slackware linux distribution: I'm actually using just a very small subset of the scripts hosted here and tofuenv is not between them.
it could be the maintainer of tofuenv on the main repository, SlackBuilds.org, might be interested in your tool so I suggest you to direct your invite to him (you could find his contact information in the tofuenv.info file).
