### ISSUE TITLE
yed slackbuild need update version

### ISSUE THREAD

**Issue by rizitis** [Ponce/slackbuilds#236]
Hello! 
Although its not current issue in LQ was mentioned as issue for current .
But I think its wrong, because the problem is that source package version is removed upstream so even for 15.0 must be an issue...
Any way this version builds fine in current with existing SlckaBuild. 
`https://www.yworks.com/resources/yed/demo/yEd-3.24.zip`

**Comment by Ponce** [comment]
hi @rizitis , you should report this to the maintainer, I'm sorry but it's not pertinent for this repository...
