### ISSUE TITLE
cutadapt need update version for current. 

### ISSUE THREAD

**Issue by rizitis** [Ponce/slackbuilds#238]
Hello ponce this is my last "commit" I m just trying to help...
There is a mismatch between python 3.11  version of current and the version of the package in SBo.
But new package version builds fine for current. 
`https://files.pythonhosted.org/packages/cb/15/85799e7fa1dfb86b8f79f8f98902b28003a054c46447a0580f21e535dbf3/cutadapt-4.9.tar.gz`

Only issue is found is that I had to remove CITATIONS from SlackBuild in docs sections,  from cp -a $DOCS  PKG/DOCS...

**Comment by Ponce** [comment]
Thanks, pushed this too!
