### ISSUE TITLE
"mumble" -current issues

### ISSUE THREAD

**Issue by RSKYS** [Ponce/slackbuilds#240]
Hi, I noticed **mumble v1.5.613** on this repo failed to build using **poco v1.12.5**.
I downgraded poco to version **1.12.4** on my repo and it built again without issue (Noticed from slackel repo, they're still on lower edition).

**Comment by djemos** [comment]
https://slackware.uk/slackel/source/extra/poco/
https://slackware.uk/slackel/x86_64/current/slackel/extra/poco-1.13.3-x86_64-1dj.txz
https://slackware.uk/slackel/i486/current/slackel/extra/poco-1.13.3-i586-1dj.txz

https://slackware.uk/slackel/source/extra/mumble-server/
https://slackware.uk/slackel/x86_64/current/slackel/extra/mumble-server-1.5.634-x86_64-2dj.txz
https://slackware.uk/slackel/i486/current/slackel/extra/mumble-server-1.5.634-i586-2dj.txz

https://slackware.uk/slackel/source/extra/mumble/1,5.634/ 
https://slackware.uk/slackel/x86_64/current/slackel/extra/mumble-1.5.634-x86_64-2dj.txz
https://slackware.uk/slackel/i486/current/slackel/extra/mumble-1.5.634-i586-2dj.txz

**Comment by Ponce** [comment]
hi @RSKYS ,

I'm not able to reproduce your error: mumble built fine here with the newer poco on current.

**Comment by RSKYS** [comment]
> I'm not able to reproduce your error: mumble built fine here with the newer poco on current.

That's strange, I will write you exact error if I rebuilt again.

> FWIW, as @djemos linked, looks like on the slackel repo they are on an even higher versioned release...

1.13.3 is their new release, but I'm not using slackel either way; I prefer scripts.
Also downgrade fixed the issue in my case, I seem not be able to see 1.13.3 changes to merge to my builds; and I'm not in rush for higher releases.

**Comment by Ponce** [comment]
> > I'm not able to reproduce your error: mumble built fine here with the newer poco on current.
> 
> That's strange, I will write you exact error if I rebuilt again.

please do that always as it might give hints on why it fails.

also remember to try your builds on a fresh (no additional packages or customizations) and full installation of slackware current: please don't report here if this prerequisite is not satisfied...

**Comment by RSKYS** [comment]
> please do that always as it might give hints on why it fails.

Yeah, my bad

> also remember to try your builds on a fresh (no additional packages or customizations) and full installation of slackware current: please don't report here if this prerequisite is not satisfied...

I always use latest official installation, nothing out of ordinary on that part.
Seems for whatever reason it's been temporary issue, I'll catch next issues with details!
