### ISSUE TITLE
ktsuss

### ISSUE THREAD

**Issue by rizitis** [Ponce/slackbuilds#242]
```
patch -p0 < $CWD/ktsuss.patch
patch -p0 < $CWD/su_backend.patch
patch -p0 < $CWD/su_backend_h.patch
```
[ktsuss.patch.txt](https://github.com/user-attachments/files/16698786/ktsuss.patch.txt)
[su_backend.patch.txt](https://github.com/user-attachments/files/16698787/su_backend.patch.txt)
[su_backend_h.patch.txt](https://github.com/user-attachments/files/16698788/su_backend_h.patch.txt)

**Comment by Ponce** [comment]
hi @rizitis ,

the maintainer abandoned ktsuss (there's a ML message of a few days ago), so if it doesn't build and nobody is interested in maintaining it I'll just remove it...

**Comment by rizitis** [comment]
Probably i m the only one who use it. Since i cant maintain packages for Slackware-stable... Removed is the correct action. Thanks.
