### ISSUE TITLE
grpc build broken

### ISSUE THREAD

**Issue by kovmir** [Ponce/slackbuilds#246]
```CMake Error at /usr/lib64/cmake/utf8_range/utf8_range-targets.cmake:95 (message):
  The imported target "utf8_range::utf8_validity" references the file

     "/usr/lib64/libutf8_validity.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/lib64/cmake/utf8_range/utf8_range-targets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/lib64/cmake/utf8_range/utf8_range-config.cmake:7 (include)
  /usr/lib64/cmake/protobuf/protobuf-config.cmake:12 (find_package)
  cmake/protobuf.cmake:58 (find_package)
  CMakeLists.txt:377 (include)```

**Comment by Ponce** [comment]
Hi @kovmir ,

I'm not able to reproduce: here grpc builds fine on slackware64-current...

**Comment by kovmir** [comment]
Can you please give a hint where to look? I have a fresh -current with all packages updated, and everything installed except `xfce` and `kde` package sets.

**Comment by Ponce** [comment]
frankly I don't know: I would just check if your protobuf is the one shipped with current, but other than that I have no idea...

**Comment by kovmir** [comment]
I tried deleting and reinstalling it, does not help.

**Comment by Ponce** [comment]
@kovmir: the only platform supported by this repository is a complete and fresh (latest version, no additional packages) installation of Slackware current.

I'm sorry but personal installations are not supported: please refer to the [wiki](/Ponce/slackbuilds/wiki) and the [dedicated topic on LQ](https://www.linuxquestions.org/questions/slackware-14/sbo-scripts-not-building-on-current-read-1st-post-pls-4175561999/) (same prerequisites apply) for more informations.
