### ISSUE TITLE
ngtcp2 need update

### ISSUE THREAD

**Issue by rizitis** [Ponce/slackbuilds#248]
ngtcp2 is not building for current.
version 1.8.0 builds fine.

---
 
you can just update version for stock SlackBuild or use this edited slackbuild which using chrpath (dynamic linker path removal)
```
Slackware package /tmp/ngtcp2-1.8.0-x86_64-1_SBo.tgz created.
WARNING: detected at least one insecure /tmp rpath:
WARNING: */tmp* rpath found in ./usr/bin/gtlsclient: RPATH /tmp/SBo/ngtcp2-1.8.0/build/crypto/gnutls:/tmp/SBo/ngtcp2-1.8.0/build/lib

```
[ngtcp2.SlackBuild.zip](https://github.com/user-attachments/files/17350006/ngtcp2.SlackBuild.zip)

**Comment by Ponce** [comment]
thanks, [pushed](/Ponce/slackbuilds/tree/ngtcp2)!
