### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by rizitis** [Ponce/slackbuilds#254]
hello, docker need update to build in current (go version go version go1.22.7 linux/amd64)
```
VERSION=${VERSION:-27.3.1}
GITHASH=${GITHASH:-41ca978}
```

**Comment by Ponce** [comment]
Hi @rizitis , I'm not able to reproduce your error, it seems that version 27.2.0 (the one on SBo) builds fine with google-go-lang 1.22.7 (still the same as SBo) here...

**Comment by rizitis** [comment]
Ok @Ponce . I dont know why I couldn't... sorry for noise
