### ISSUE TITLE
python3-pyicu info file need edit.

### ISSUE THREAD

**Issue by rizitis** [Ponce/slackbuilds#262]
Download url is missing a `"` at the end. This happens only for ponce current repo. In [SBo](https://github.com/SlackBuildsOrg/slackbuilds/blob/master/python/python3-pyicu/python3-pyicu.info) its ok

https://github.com/Ponce/slackbuilds/blob/current/python/python3-pyicu/python3-pyicu.info
```
PRGNAM="python3-pyicu"
VERSION="2.14"
HOMEPAGE="https://github.com/ovalhub/pyicu"
DOWNLOAD="https://files.pythonhosted.org/packages/52/21/4e9b0a3ace3027fc63107fa2b5d6e66e321e104da071d787856962fbad52/PyICU-2.14.tar.gz
MD5SUM="7ec5ad0d62a2a27f919ca8a775352a71"
DOWNLOAD_x86_64=""
MD5SUM_x86_64=""
REQUIRES=""
MAINTAINER="Heinz Wiesinger"
EMAIL="pprkut@slackbuilds.org"
```

**Comment by Ponce** [comment]
thanks a lot @rizitis , @fourtysixand2 (that I thank too) already reported this via mail and I fixed it some hours ago!
