### ISSUE TITLE
qt-creator: qbsprojectmanager fails to compile under gcc 7.2.0

### ISSUE THREAD

**Issue by srandalls** [Ponce/slackbuilds#36]
### Command
`g++ -c -O2 -march=i586 -mtune=i686 -O2 -march=i586 -mtune=i686 -std=gnu++1y -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -D_REENTRANT -fPIC -DQBS_ENABLE_PROJECT_FILE_UPDATES -D'RELATIVE_PLUGIN_PATH="../lib/qtcreator/plugins"' -D'RELATIVE_LIBEXEC_PATH="../libexec/qtcreator"' -D'RELATIVE_DATA_PATH="../share/qtcreator"' -D'RELATIVE_DOC_PATH="../doc/qt-creator-4.3.1"' -DIDE_LIBRARY_BASENAME=\"lib\" -DQT_CREATOR -DQT_NO_CAST_TO_ASCII -DQT_RESTRICTED_CAST_FROM_ASCII -DQT_DISABLE_DEPRECATED_BEFORE=0x050600 -DQT_USE_FAST_OPERATOR_PLUS -DQT_USE_FAST_CONCATENATION -DQMAKE_AS_LIBRARY -DPROPARSER_THREAD_SAFE -DPROEVALUATOR_THREAD_SAFE -DPROEVALUATOR_CUMULATIVE -DPROEVALUATOR_DUAL_VFS -DPROEVALUATOR_SETENV -DQBS_VERSION=\"1.8.1\" -DQBS_VERSION=\"1.8.1\" -DQBS_INSTALL_DIR=\"/usr\" -DQBSPROJECTMANAGER_LIBRARY -DQT_NO_DEBUG -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CONCURRENT_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../../src -I../../../src -I../../libs -I/tmp/SBo/qt-creator-4.3.1/tools -I../../plugins -I../../shared -I../../libs/3rdparty -I. -isystem /usr/include/qbs -isystem /usr/include -isystem /usr/include/qbs -isystem /usr/include -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtConcurrent -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -I.moc/release-shared -I.uic -I/usr/lib/qt5/mkspecs/linux-g++ -o .obj/release-shared/customqbspropertiesdialog.o customqbspropertiesdialog.cpp`
### Error Message
`In file included from /usr/include/c++/7.2.0/bits/stl_algo.h:59:0,`
`                 from /usr/include/c++/7.2.0/algorithm:62,`
`                 from /usr/include/qt5/QtCore/qglobal.h:94,`
`                 from /usr/include/qt5/QtCore/qatomic.h:41,`
`                 from /usr/include/qt5/QtCore/qvariant.h:43,`
`                 from /usr/include/qt5/QtCore/QVariantMap:1,`
`                 from customqbspropertiesdialog.h:28,`
`                 from customqbspropertiesdialog.cpp:26:`
`/usr/include/c++/7.2.0/cstdlib:75:15: fatal error: stdlib.h: No such file or directory`
` #include_next <stdlib.h>`
`               ^~~~~~~~~~`
`compilation terminated.`
`make: *** [Makefile:1171: .obj/release-shared/customqbspropertiesdialog.o] Error 1`

### Issue
From what I have read online, this is a recurring issue when compiling Qt projects with gcc, because of the `-isystem /usr/include` option passed to g++ by `qmake` - generated `Makefile`, e.g. [https://bugreports.qt.io/browse/QTBUG-53375](https://bugreports.qt.io/browse/QTBUG-53375):

### Private Solution
I first solved this for myself by editing `/tmp/SBo/qt-creator-4.3.1/src/plugins/qbsprojectmanager/qbsprojectmanager.pro` and re-running `qmake` within that directory. Following advice I read online, I merely added a line at the end of that file:
`QMAKE_CFLAGS_ISYSTEM=`

Then I was able to resume compiling successfully. [BTW: In the case of a SlackBuild crash, I comment out the lines to get me to where the build left off, so that the script doesn't start over from the top.]

After that worked, I removed `.../qbsprojectmanager/Makefile`, reverted `.../qbsprojectmanager/qbsprojectmanager.pro`, and edited `qt-creator.SlackBuild`, inserting the following three lines just before `qmake-qt5 ...` (line 119):
`--------------------------------------------------------------------------------`
`# Allow g++ to find <stdlib.h>`
`echo 'QMAKE_CFLAGS_ISYSTEM=' >> ./src/plugins/qbsprojectmanager/qbsprojectmanager.pro`
` `
`--------------------------------------------------------------------------------`
This worked.

### Suggested Public Solution
I recommend editing `qt-creator.SlackBuild` in the manner I described above for the current release.

**Comment by Ponce** [comment]
Thanks @srandalls !
I pushed the fix in a dedicated [qt-creator branch](/Ponce/slackbuilds/tree/qt-creator).
