### ISSUE TITLE
Kodi: Compiling issue

### ISSUE THREAD

**Issue by Jigoku** [Ponce/slackbuilds#37]
on -current, i cannot seem to get past this. I have also tried rebuilding all dependencies in order, but still the same output:
```xbmc-17.4-Krypton/xbmc/windows/GUIWindowSystemInfo.h
xbmc-17.4-Krypton/xbmc/windows/GUIWindowWeather.cpp
xbmc-17.4-Krypton/xbmc/windows/GUIWindowWeather.h
xbmc-17.4-Krypton/xbmc/windows/Makefile
chmod: cannot operate on dangling symlink './tools/depends/target/ffmpeg/ffmpeg-3.1.9-Krypton-17.4.tar.gz'
patching file xbmc/filesystem/FTPParse.cpp
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
3 out of 3 hunks ignored -- saving rejects to file xbmc/filesystem/FTPParse.cpp.rej

```

**Comment by djemos** [comment]
Use kodi-17.5 and FFmpeg-3.1.11-Krypton-17.5.tar.gz ( download from here 
https://github.com/xbmc/FFmpeg/archive/3.1.11-Krypton-17.5/FFmpeg-3.1.11-Krypton.tar.gz)

Kodi 17.5 binary and source code on slackel (slackware current) 
http://www.slackel.gr/repo/source/extra/kodi/17.5/

Dimitris Tzemos


Στις 17/11/2017 08:41 πμ, ο Ricky T έγραψε:

**Comment by Ponce** [comment]
a patch that applied to a previous version was still in the repository: please try again building it, it should be ok now.
