### ISSUE TITLE
your link not work

### ISSUE THREAD

**Issue by DarthMoulByte** [Ponce/slackbuilds#38]
See project homepage http://linuxwireless.org/en/users/Drivers/b43
for technical details and copyright information.
![chrome_2018-02-04_16-26-52](https://user-images.githubusercontent.com/24207840/35783187-cc0efa28-09c8-11e8-8a9f-fb5359557324.png)

**Comment by Ponce** [comment]
Hi @DarthMoulByte, the link you are reporting is the homepage of a script hosted by SlackBuilds.org, I just fork their repository here with changes for using it with slackware current and the b43* scripts hasn't been changed at all.
I suggest you to report issues related with broken links on the slackbuilds-users mailing list
https://lists.slackbuilds.org/mailman/listinfo/slackbuilds-users
