### ISSUE TITLE
Freealut: download link does not work

### ISSUE THREAD

**Issue by mdrights** [Ponce/slackbuilds#39]
Hi,
I found the link for downloading the source package of Freealut returns 403. 
See its info file:
https://github.com/Ponce/slackbuilds/blob/fa5bce6cc6014f90b8d5d2c4ae3fb1ceb08bbe99/libraries/freealut/freealut.info

And current I am not able to find a valid URL offering source of Freealut. Anyone has this resource? 

Many thanks

**Comment by Ponce** [comment]
Hi @mdrights , the freealut link you refer too is working fine here.
BTW, I haven't changed the download link from what is on SBo, so you should eventually report any broken links on the slackbuilds-users mailing list, not here...
