### ISSUE TITLE
gtkpod broken by its dependencies after -current 20150421

### ISSUE THREAD

**Issue by denydias** [Ponce/slackbuilds#4]
After the recent big package upgrade on -current at 20150421, `gtkpod` dependencies fails to build.

The complete `gtkpod` queue is:

```
vte3
libgda
gtksourceview3
gdl
autogen
anjuta
gtkpod
```

`vte3` and `libgda` builds fine with this:

```
# sbopkg -i vte3
# LDFLAGS="-L/usr/lib64" sbopkg -i libgda
```

Then `gtksourceview` fails with this:

```
# sbopkg -i gtksourceview3
...
make[4]: Entrando no diretório `/dev/shm/gtksourceview-3.8.2/gtksourceview'
  CC       libgtksourceview_3_0_la-gtksourcebuffer.lo
  CC       libgtksourceview_3_0_la-gtksourcecompletion.lo
  CC       libgtksourceview_3_0_la-gtksourcecompletioncontext.lo
  CC       libgtksourceview_3_0_la-gtksourcecompletioninfo.lo
  CC       libgtksourceview_3_0_la-gtksourcecompletionitem.lo
gtksourcecompletionitem.c: In function 'gtk_source_completion_item_new_from_stock':
gtksourcecompletionitem.c:381:2: error: unknown type name 'GtkStockItem'
  GtkStockItem stock_item;
  ^
gtksourcecompletionitem.c:395:3: error: implicit declaration of function 'gtk_stock_lookup' [-Werror=implicit-function-declaration]
   if (label == NULL && gtk_stock_lookup (stock, &stock_item))
   ^
gtksourcecompletionitem.c:395:3: warning: nested extern declaration of 'gtk_stock_lookup' [-Wnested-externs]
gtksourcecompletionitem.c:397:22: error: request for member 'label' in something not a structure or union
    label = stock_item.label;
                      ^
cc1: some warnings being treated as errors
make[4]: ** [libgtksourceview_3_0_la-gtksourcecompletionitem.lo] Erro 1
make[4]: Saindo do diretório `/dev/shm/gtksourceview-3.8.2/gtksourceview'
make[3]: ** [all-recursive] Erro 1
make[3]: Saindo do diretório `/dev/shm/gtksourceview-3.8.2/gtksourceview'
make[2]: ** [all] Erro 2
make[2]: Saindo do diretório `/dev/shm/gtksourceview-3.8.2/gtksourceview'
make[1]: ** [all-recursive] Erro 1
make[1]: Saindo do diretório `/dev/shm/gtksourceview-3.8.2'
make: ** [all] Erro 2
```

I could not find a fix for that so I can't move on with the other dependencies.  At this moment, `gtkpod` is a no go under an updated -current.

Please let me know if you need further assistance on tests and debug. I'm fully available to sort this out.

**Comment by Ponce** [comment]
the problem is that in current with the update of april 21th the base component of the gnome platform has been bumped to 3.14 so the other component should be aligned: I just version bumped 3 packages (anjuta, gdl and gtksourceview3) and doing so I introduced an additional dependency (glade, needed for the newer gtksourceview3), then I tried to build gtkpod and it went fine.
Please, resync the repository and try again (don't forget the new dependency).

**Comment by denydias** [comment]
Hi @Ponce,

I'm resynching the repo right now to build the packages as per your instructions. I let you know as soon as I finish. Thank you very much for the always quick feedback.

**Comment by denydias** [comment]
Hi @Ponce,

The new scripts worked perfectly. Thank you very much for the quick fix.
