### ISSUE TITLE
Virtualbox-addons: 

### ISSUE THREAD

**Issue by mdrights** [Ponce/slackbuilds#43]
Compiling Virtualbox-addons failed on a clean, newly-installed Slackware-current system (just two days ago).
I used the Slackbuild here in Virtualbox-addons branch with version 5.2.8.

`gcc version 8.1 found, expected gcc 4.x ... 7.x` 

I know that lately we use gcc 8.1, so how could we fix this issue?

Thanks a million.

**Comment by Ponce** [comment]
try adding this line before the one with "configure" in the SlackBuild, seems to be safe
`sed -i "s|cc_maj -gt 7|cc_maj -gt 8|" configure`

**Comment by Ponce** [comment]
fixed in the repository.
