### ISSUE TITLE
ncbi-blast-plus (academic) - binaries require older libidn.so.11

### ISSUE THREAD

**Issue by edrozenberg** [Ponce/slackbuilds#44]
This slackbuild creates a package using pre-compiled binaries from ncbi. Those binaries unfortunately require `libidn.so.11` (from libidn-1.34.tar.gz), whereas slackware-current now ships only `libidn.so.12` (from libidn-1.35.tar.gz) since some weeks ago. So the binaries do not work as is on Slackware-current:

```
./blastn: error while loading shared libraries: libidn.so.11: cannot open shared object file: No such file or directory
```

My workaround: used the libidn slackbuild from slackware-current sources, along with libidn-1.34.tar.gz source code, to build the library `libidn.so.11.6.18` and also added a symlink to it:
```
/usr/lib64/libidn.so.11.6.18
/usr/lib64/libidn.so.11 -> libidn.so.11.6.18
```

Not sure of the best approach for the slackbuilds.org slackbuild. Maybe ncbi will release updated binaries later? Otherwise would mean having to compile `ncbi-blast-plus` from source instead of using the pre-compiled binaries.

**Comment by Ponce** [comment]
as the maintainer choose to repackage a binary maybe you should get in touch with him.
the alternatives, IMHO, should be to:
- try to repackage the available 2.8.0alpha ( ftp://ftp.ncbi.nih.gov/blast/executables/blast+/2.8.0alpha/ncbi-blast-2.8.0-alpha+-x64-linux.tar.gz ) hoping that it links to newer libraries (not tried here);
- like you said, build it from sources.
but it's better if the maintainer handles this, in the meantime I'll just remove it from the repository for current (as it can't work as-is).
