### ISSUE TITLE
Spotify segfaults

### ISSUE THREAD

**Issue by bvandonselaar** [Ponce/slackbuilds#45]
I am on Slackware64-current and after a update since a couple of days. It's not starting anymore. I ran spotify in the terminal and this was the output:

``/opt/spotify/usr/bin/spotify: /usr/lib64/libcurl.so.4: no version information available (required by /opt/spotify/usr/bin/spotify)
/usr/bin/spotify: line 2:  2821 Segmentation fault      /opt/spotify/usr/bin/spotify "$@"
``

I am not really great in debugging with things like missing libraries or unexpected segfaults when launching a application build with a slackbuild script.
Btw, i can still build and install spotify with the slackbuild, but it's just not launching. I have curl/libcurl installed on my system.

**Comment by Ponce** [comment]
if you want to test something I tried to upgrade it to 1.0.89: modify the SlackBuild like you can see here

http://cgit.ponce.cc/slackbuilds/commit/?h=spotify

this will be an one-time thing...

**Comment by bvandonselaar** [comment]
Ah thank you a lot for even taking the time for my "complaining". I also tried to just use a newer Spotify but that did not work. I see that you made more changes to the SlackBuild than i did so i will be testing it immediatly. Sorry if this was not the place to open this issue. I saw that LQ gets used a lot for discussing your repo, so would that be a better place for these kind of questions?

**Comment by Ponce** [comment]
no prob: yes, discussing this kind of problems (broken SlackBuilds/functionality of SlackBuilds on current) on LQ is actually better.

...but when I said an one-time thing I meant regarding specifically to spotify: it started using some libraries available only on ubuntu so that maintaining this to run on other platforms will be painful in the future and I don't know if the maintainer will want to do this (I surely won't :) ).

**Comment by bvandonselaar** [comment]
I have tested it and it works. First it did not launch, but i installed [rtmpdump](https://slackbuilds.org/repository/14.2/multimedia/rtmpdump/?search=rtmpdump) from your slackbuild repo(because there was a library missing on launch) and it worked. I'm curious how/if the spotify slackbuild will be maintaint. Thanks for your help and goodbye! :)
