### ISSUE TITLE
unable to build package dahdi-complete

### ISSUE THREAD

**Issue by maha-fyi** [Ponce/slackbuilds#49]
I was unable to build package on -current with sbopkg. I also tried to build from source using the downloaded source tarball.

What did work for me was source build using git clone dahdi-linux and dahdi-tools. I did have to copy over libtonezone* from /usr/lib to /usr/lib64 before dahdi_cfg worked.

**Comment by Ponce** [comment]
I just pushed an update to 3.0.0 in [a dedicated branch](/Ponce/slackbuilds/tree/dahdi-complete/), it will go in the main current one at the next merge.
