### ISSUE TITLE
NetworkManager-vpnc build problem

### ISSUE THREAD

**Issue by sairum** [Ponce/slackbuilds#55]
NetworkManager-vpnc SlackBuild fails with

```
[...]
checking for LIBNMA... yes
checking for LIBSECRET... yes
checking for LIBNM_GTK... no
configure: error: Package requirements (libnm-gtk >= 1.2.0) were not met:

No package 'libnm-gtk' found
```

Apparently, _libnm-gtk_ used to live in _network-manager-applet_ slackware package, but it is not there anymore.

**Comment by sairum** [comment]
Apparently, the solution is to pass 

`--without-libnm-glib \`

in SlackBuild .configure command. In AlienBob's ktown (running in current) the nm applet can now configure a vpn connection using vpnc!

**Comment by Ponce** [comment]
thanks for reporting!
I just pushed the modification in a dedicated branch.
