### ISSUE TITLE
sorry but i get this error

### ISSUE THREAD

**Issue by fastname3** [Ponce/slackbuilds#56]
I try to install amap, or arj like this
 slackrepo build arj

i get this error:
ERROR: Failed to mount /tmp/slackrepo.4VbKcc/chrootdir/

with dmesg \ tails this:
[46313.083982] overlayfs: filesystem on '/tmp/ponce/slackrepo.oy2l6T/ovldir/dirty' not supported as upperdir
[46408.679090] overlayfs: filesystem on '/tmp/ponce/slackrepo.0sTXef/ovldir/dirty' not supported as upperdir

and i cant continue installing nothing, all time the same error
how i can fix please

**Comment by Ponce** [comment]
hi @fastname3 , I think this has nothing to do with my repository but it's instead related to the filesystem you are using for your /tmp directory while running slackrepo.

**Comment by fastname3** [comment]
I thought you would understand something about the subject overlayfs and I could help forgive
I'll search on my own,

Slackrepo choose the TMP directory I did not choose,
I use a normal  TMP slackware 14.2 in /,
(not slackware current)
why Slackrepo need to use overlayfs?? I do not know anything that uses that I have no idea how to fix it 

thanks
