### ISSUE TITLE
local slackbuild file not taken

### ISSUE THREAD

**Issue by janemba** [Ponce/slackbuilds#57]
Hello,

I have an issue in two different box with SBo-git repository. When I set this repository for sbopkg, I noticed the local SlackBuild file is never taken by sbopkg script.

I used to make it the following way:
```
  $ cp /var/lib/sbopkg/SBo-git/network/foo/foo.SlackBuild{.sbopkg}
```
Then I modify the file and I execute the following command-line:
```
  $ sbopkg -i foo
```
Finally, the local file is not loaded.

**Comment by Ponce** [comment]
This thing you are reporting is not related to my repository but to sbopkg, so you better post an issue [here](/sbopkg/sbopkg/issues)
