### ISSUE TITLE
spotify - missing libnettle.so.6

### ISSUE THREAD

**Issue by MikeTatsuo** [Ponce/slackbuilds#59]
Hello,

firstly I want to thank you for your work in this repo.

I'm having an issue trying to execute Spotify, I followed the instructions on the wiki to update your repo on sbopkg, installed rtmpdump and Spotify from sbopkg, but when I try to execute Spotify gives me the following error

```
/opt/spotify/usr/bin/spotify: error while loading shared libraries: libnettle.so.6: cannot open shared object file: No such file or directory
```

I checked and I don't have libnettle.so.6, but instead I have installed in my Slackware-current libnettle.so.7, looks like I installed the most recent version of current with Nettle 3.5.1 which changed the library to libnettle.so.7

Changelog from slackware-current (https://mirrors.slackware.com/slackware/slackware-current/ChangeLog.txt)
```
.
.
.
+--------------------------+
Thu Jun 27 19:07:20 UTC 2019
ap/vim-8.1.1601-i586-1.txz:  Upgraded.
  Built with --disable-canberra. Thanks to Markus Wiesner.
l/harfbuzz-2.5.3-i586-1.txz:  Upgraded.
n/nettle-3.5.1-i586-1.txz:  Upgraded.
n/nftables-0.9.1-i586-1.txz:  Upgraded.
t/texlive-2019.190626-i586-1.txz:  Upgraded.
  Shared library .so-version bump.
  Thanks to Johannes Schoepfer.
xap/blueman-2.1-i586-1.txz:  Upgraded.
  Thanks to Robby Workman.
xap/vim-gvim-8.1.1601-i586-1.txz:  Upgraded.
+--------------------------+
.
.
.
```

and News for Nettle 3.5.1 (https://github.com/gnutls/nettle/blob/master/NEWS)

```
.
.
.
The shared library names are libnettle.so.7.0 and
	libhogweed.so.5.0, with sonames libnettle.so.7 and
	libhogweed.so.5.
. 
. 
.
```

Sorry for my english :grimacing:

**Comment by Ponce** [comment]
Hi Mike,

I already took care of update spotify multiple times in the past for current (see issue #45 and [this topic on LQ](https://www.linuxquestions.org/questions/slackware-14/the-build-of-ostree-fails-4175639663/#post5911983): please refer to the maintainer for an update.

**Comment by MikeTatsuo** [comment]
I see, well I just found out that they only make for Ubuntu on their spare time and because of they wanted to listen on their dev environment, I think I will stick with the web version for now then :sweat_smile:

If I find out some solution I will comment here, but for now, I will close this issue :grimacing:
Thanks for your time

**Comment by MikeTatsuo** [comment]
UPDATE: I solved the issue, thanks to the @jak3

the problem was with the /opt/spotify/usr/lib/libcurl-gnutls.so.4 which was linked to libcurl-gnutls.so.4.5.0 in the same folder, @jak3 suggested to create the file libcurl-gnutls.so.4 but linking to /usr/lib64/libcurl.so, so what I did was renamed the existing libcurl-gnutls.so.4 to libcurl-gnutls.so.4.bkp

```
mv /opt/spotify/usr/lib/libcurl-gnutls.so.4 /opt/spotify/usr/lib/libcurl-gnutls.so.4.bkp
```

and create a new link

```
ln -sf /usr/lib64/libcurl.so /opt/spotify/usr/lib/libcurl-gnutls.so.4
```

and started Spotify and worked without any issue :grimacing:
