### ISSUE TITLE
Git pull shows 'Automatic merge failed' for later pulls

### ISSUE THREAD

**Issue by edrozenberg** [Ponce/slackbuilds#63]
After I do an initial `git clone` on the ponce slackbuilds git project, when I come back some days later and do a `git pull` I always experience conflicts which trigger the error `Automatic merge failed; fix conflicts and then commit the result.`

I don't make any changes to the git checkout, and I don't remember running into this with other git clones of other projects. I'm not enough of a git expert to figure out what it is about the ponce project that prevents subsequent pulls from working properly.

For now I just delete and do a fresh git pull each time I want to update to the latest.

**Comment by edrozenberg** [comment]
Here are the conflicts I saw doing `git pull` just now:

```
CONFLICT (rename/delete): libraries/libtxc_dxtn/slack-desc deleted in HEAD and renamed to audio/DPF-Plugins/slack-desc in de6029b5d14f1a8c0ed86613966159d54f8b8c3f. Version de6029b5d14f1a8c0ed86613966159d54f8b8c3f of audio/DPF-Plugins/slack-desc left in tree.
CONFLICT (rename/delete): development/ninja/ninja.SlackBuild deleted in HEAD and renamed to audio/DPF-Plugins/DPF-Plugins.SlackBuild in de6029b5d14f1a8c0ed86613966159d54f8b8c3f. Version de6029b5d14f1a8c0ed86613966159d54f8b8c3f of audio/DPF-Plugins/DPF-Plugins.SlackBuild left in tree.
CONFLICT (rename/delete): libraries/isl/slack-desc deleted in HEAD and renamed to accessibility/sct/slack-desc in de6029b5d14f1a8c0ed86613966159d54f8b8c3f. Version de6029b5d14f1a8c0ed86613966159d54f8b8c3f of accessibility/sct/slack-desc left in tree.
CONFLICT (rename/delete): system/patchelf/patchelf.SlackBuild deleted in HEAD and renamed to accessibility/sct/sct.SlackBuild in de6029b5d14f1a8c0ed86613966159d54f8b8c3f. Version de6029b5d14f1a8c0ed86613966159d54f8b8c3f of accessibility/sct/sct.SlackBuild left in tree.
Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by Ponce** [comment]
this is the normal behaviour: the "current" branch is not updated by single commits like (probably) the other projects you mention but is deleted and recreated over the master branch applying the commits present in the other 530+ branches... so it's not possible to apply modifications to your local current branch because, also if they're named the same, they're actually two different branches.
yes, deleting and recloning is the easiest and fastest way.
