### ISSUE TITLE
mpv fails on libavfilter/libfontconfig

### ISSUE THREAD

**Issue by rpedrica** [Ponce/slackbuilds#65]
I'm trying to install mpv from sbo-git but get the following compile errors:

> Waf: Entering directory `/data/src2pkg/src2pkg.scripts.desktop/mpv/mpv-0.31.0/build'
> [1/1] Compiling version.sh
> [244/245] Linking build/mpv
> /usr/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/9.2.0/../../../../lib64/libavfilter.so: undefined reference to symbol 'FcConfigCreate'
> /usr/bin/ld: /usr/lib64/libfontconfig.so.1: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status

I'm not sure if the error originates with AlienBob's ffmpeg package (provides libavfilter.so) or the OS-provided libfontconfig package. Slackware -current as of yesterday.

**Comment by Ponce** [comment]
you should try building this using ffmpeg as provided by Slackware current

**Comment by rpedrica** [comment]
Thanks Ponce,  I switched out ffmpeg for the os-provided package. MPV requires libass so installed that via sbopkg-git (I had originally done my own package) and get the following now for mpv build:

> [245/245] Linking build/mpv
> /usr/bin/ld: video/out/vulkan/context_wayland.c.25.o: in function `wayland_vk_init':
> /tmp/SBo/mpv-0.29.1/build/../video/out/vulkan/context_wayland.c:57: undefined reference to `vkCreateWaylandSurfaceKHR'
> collect2: error: ld returned 1 exit status

 This seems to be a known issue:

https://github.com/mpv-player/mpv/issues/5749
and
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=235469

Am I missing something?

**Comment by Ponce** [comment]
this last is not a current-specific error and it should happen because you have installed in your system the package wayland-protocols: remove it and try the build again.

**Comment by mumahendras3** [comment]
Try rebuilding vulkan-sdk with -DBUILD_WSI_WAYLAND_SUPPORT=On in vulkan-sdk.SlackBuild and then try to rebuild mpv again. It works with me here (in -current with wayland installed)

**Comment by Ponce** [comment]
it seems that vulkan-sdk is built with this option now in current so this shouldn't happen anymore.
