### ISSUE TITLE
libvirt build fails because of wireshark config.h missing file

### ISSUE THREAD

**Issue by Gunbird** [Ponce/slackbuilds#69]
Hi,

In the current tree libvirt compilation fails with :
`../../tools/wireshark/src/packet-libvirt.c:21:10: fatal error: wireshark/config.h: No such file or directory`

This can be fixe just by adding this header in the wireshark package : 
`install -m644 ws_diag_control.h ws_symbol_export.h build/config.h $PKG/usr/include/$PRGNAM`

I tested it here and it works.

Regards

**Comment by Ponce** [comment]
hi @Gunbird ,
this is not an issue specific to this repository but it applies to wireshark and libvirt also in the main SlackBuilds.org's one.
I suggest you getting in touch with the wireshark maintainer on SBo and report the fix to him, thanks!
