### ISSUE TITLE
slackbuild for vala?

### ISSUE THREAD

**Issue by Ndolam** [Ponce/slackbuilds#72]
First, thanks for making this available.  

You have the slackbuild for shotwell, which requires libgee, which you also have.
But libgee requires vala, which you don't have.
Does this fall into the "haven't got around to it yet" category or the "it is broken" category?
Thanks.

**Comment by Ponce** [comment]
neither, that is part of the "stuff that has been already added to current so it has been removed from here to avoid duplication" category.
regarding why vala hasn't been removed from the REQUIRES variable of the libgee.info file please read the [wiki homepage here](https://github.com/Ponce/slackbuilds/wiki).
