### ISSUE TITLE
the boost patch needs updated

### ISSUE THREAD

**Issue by KenCoble** [Ponce/slackbuilds#74]
the latest boost 1.73.0 upated on 9th of May breaks gnuradio, and the patch wont allow a rebuild, needs updated patch

**Comment by Ponce** [comment]
thanks for reporting: all is fixed in the [gnuradio branch](https://github.com/Ponce/slackbuilds/tree/gnuradio).
the fixes will go in the main branch ("current") at the next global update (most probably next week).
