### ISSUE TITLE
boost-1.73.0 breaks this too

### ISSUE THREAD

**Issue by KenCoble** [Ponce/slackbuilds#75]
you know it

**Comment by Ponce** [comment]
no, I don't: which script are you speaking about?

**Comment by KenCoble** [comment]
the gnuradio patches worked good with gnuradio, but now i think gr-osmosdr needs patched, the terminal echoed things like endian and boost not being right, so i think gr-osmosdr will have to be patched too

**Comment by Ponce** [comment]
gr-osmosdr is fixed too in [his own branch](https://github.com/Ponce/slackbuilds/tree/gr-osmosdr).
as with gnuradio the fixes will go in the main branch ("current") at the next global update (most probably next week).
