### ISSUE TITLE
Confusing wording

### ISSUE THREAD

**Issue by Ndolam** [Ponce/slackbuilds#81]
(a) Thanks for your efforts with this

(b) What does "on the current branch will be merged in one commit the modified build scripts (all the other branches);" mean?

**Comment by Ponce** [comment]
as you can see inspecting the various branches (see https://github.com/Ponce/slackbuilds/branches) every modified build script (0ad, for example) has a dedicated branch to make useful checking which are the modifications done to a single Slackbuild.
as this is a fork of the main SBo repository, at every new tag of the main SBo repository "master" branch I will delete the local "current" branch here, rebase all the single branches for every script against the new SBo's master branch and the "merge --squash" in a new local "current" branch all the individual branches here in a single commit with all the modifications.

**Comment by Ndolam** [comment]
Hmmm... I'm not trying to be The Grammar Police, but the words I asked about still don't parse (for me), even after reading your reply.  Perhaps "the current branch will be merged in one commit with the modified build scripts (of all the other branches);"

**Comment by Ponce** [comment]
it's not the current branch that will be merged... it's the other branches that will be merged on it.

**Comment by Ndolam** [comment]
Is "merged" not a symmetric relation?  In any case, how about
"the modified build scripts (of all the other branches) will be merged with the current branch in one commit".

**Comment by Ponce** [comment]
I'm afraid you might not understand how merging in git works...
BTW, the phrase you wrote could be adapted like "the modified build scripts in the various branches will be merged in the current one in one commit", but IMHO it's not that different with the one you are trying to substitute...

**Comment by Ndolam** [comment]
It is quite possible I don't understand how merging in git works.
"I think I am beginning to get a glimpse of what you mean by "on the current branch will be merged".  If you mean by that what I now think you mean by that, let me say that I think 99/100 native English speakers would have a hard time with that sentence structure.  Going out on a limb, I am guessing you are Italian, and perhaps that structure is the way to say it in Italian.  I would say that for native English speakers, my last suggestion is far more natural.  And your most recent wording is fine, although replacing "one in one" with "branch in one" would be better.

Let me emphasize that I am trying to be helpful; I'm not trying to bleed over your wording, and I genuinely had no idea what the original sentence is trying to convey (although now I finally do understand it, thanks.)

Cheers

**Comment by Ponce** [comment]
I have modified that line with the following one: 'the "current" branch will be deleted and the modified build scripts in the various branches will be merged in a newly created "current" one with a single commit'

**Comment by Ndolam** [comment]
Thanks!  Much better (IMHO).
