### ISSUE TITLE
Ristretto needs to be updated to 0.10.0 for Xfce 4.16

### ISSUE THREAD

**Issue by PegasusAndMe** [Ponce/slackbuilds#97]
Ristretto 0.8.4 requires libxfce4ui-1.so which has been replaced/upgraded in Xfce 4.16. I was able to modify the existing Slackbuild for Ristretto locally with just a bump in version number and md5sum for Ristretto 0.10.0.

**Comment by Ponce** [comment]
thanks, pushed the update in a dedicated ristretto branch!
